[normal]
list = ["position", "gesture", "interaction", "activity"]
position = ["standing", "sitting", "walking", "running"]
gesture = ["waving", "pointing", "adjusting hair"]
interaction = ["holding hand"]
activity = ["drinking", "reading"]

[preliminary]
list = ["masturbation", "handjob", "paizuri", "fellatio"]
masturbation = ["fingering"]
handjob = ["handjob"]
paizuri = ["paizuri"]
fellatio = [
  "fellatio",
  "irrumatio",
  "deepthroat",
  "surprise deepthroat",
  "licking penis",
]

[main]
list = ["doggystyle", "cowgirl", "standing-sex", "piledriver"]
doggystyle = [
  "doggystyle",
  "top-down bottom-up",
  "face down",
  "prone bone",
  "bent over",
]
cowgirl = ["girl on top"]
standing-sex = ["standing sex"]
piledriver = ["pilediver"]

[finisher]
cum = ["cum"]
