[normal]
position = ["standing", "sitting", "walking", "running"]
gesture = ["waving", "pointing", "adjusting hair"]
interaction = ["holding hand"]
activity = ["drinking", "reading"]

[nsfw]
list = ["preliminary", "main"]
preliminary = ["fingering", "handjob", "fellatio", "licking penis", "paizuri"]
main = [
  "doggystyle",
  "cowgirl",
  "reversed cowgirl",
  "piledriver",
  "suspended congress",
  "full nelson",
]

[nsfw.settings]
hide_male = false
penis_size = ["small:0.5", "normal", "large", "huge:0.5"]
testicles_size = ["small:0.5", "normal", "large", "huge:0.5"]
insertion = ["vaginal", "anal"]
sweat = 1
cum = 1
pussy_juice = 1
