[normal]
position = ["standing", "sitting", "walking", "running", "lying"]
action = ["waving", "adjusting hair", "holding hand", "drinking", "reading"]

[nsfw.settings]
hide_male = false
penis_size = ["small?0.5", "", "large", "huge?0.5"]
testicles_size = ["small?0.5", "", "large", "huge?0.5"]
insertion = ["vaginal", "anal"]
sweat = 1
cum = 1
pussy_juice = 1

[nsfw.actions]
teasing = ["flashing"]
preliminary = ["fingering", "handjob", "fellatio", "licking penis", "paizuri"]
position = [
  "doggystyle",
  "cowgirl",
  "reversed cowgirl",
  "piledriver",
  "suspended congress",
  "full nelson",
]
