define:
  &colors [
    aqua,
    black,
    blue,
    brown,
    green,
    grey,
    orange,
    pink,
    purple,
    red,
    white,
    yellow,
  ]

vest:
  types: [vest, waistcoat]
  colors: *colors
top:
  types: [shirt, blouse, sweater, jacket, coat]
  colors: *colors
bottom:
  types: [pants, shorts, skirt]
  colors: *colors
