prefix = "score_9, score_8_up, score_7_up, source_anime"
#negative = "score_6, score_5, score_4"
protagonists = ["1girl", "1girl, 1boy"]

[camera]
framings = ["close-up", "portrait", "upper body", "full body"]
angles = [
    "from above",
    "from below",
    "from side",
    "from behind",
    "straight on",
    "pov",
]
