time = ["day", "night", "dawn", "dusk", "sunset", "sunrise"]
weather = ["sunny", "cloudy", "rainy", "snowy"]

[locations]
list = ["indoors", "outdoors"]

[locations.indoors]
list = ["house", "public"]
house = ["bedroom", "living room", "kitchen", "bathroom"]
public = ["office", "library"]

[locations.outdoors]
tags = ["forest", "mountain", "beach"]

[effects]
probability = 0.5
repeat = [1, 2]
tags = ["light particles", "light rays"]
